language: scala
sudo: false

services:
  - docker

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
#    - /tmp/receipts-target
#    - /tmp/receipts-target-tests

before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

script: bash ci.sh
