language: scala
jdk: oraclejdk8
sudo: false

addons:
  apt:
    packages:
      - imagemagick

scala:
   - 2.11.8

services:
  - docker

branches:
  only:
    - master

script: rm -rf /home/travis/.ivy2/cache && sbt test && sbt integrate && sbt assembly && bash publish.sh
