version: '3'

services:

  app:
    image: leonti/receipts-rest-service:${VERSION:-0}
    build:
      context: /tmp/receipts-target
    volumes:
      - /tmp/receipt-uploads:/tmp/receipt-uploads
    ports:
      - "9000:9000"
    environment:
      - MONGODB_DB
      - MONGODB_USER
      - MONGODB_PASSWORD
      - MONGODB_SERVER
      - S3_BUCKET
      - S3_ACCESS_KEY
      - S3_SECRET_ACCESS_KEY
      - S3_CUSTOM_ENDPOINT
      - S3_REGION
      - GOOGLE_CLIENT_ID
      - UPLOADS_FOLDER
      - AUTH_TOKEN_SECRET
      - GOOGLE_API_CREDENTIALS
      - USE_OCR_STUB
      - OCR_SEARCH_HOST
      - OCR_SEARCH_API_KEY

  assembly:
    image: leonti/sbt_1.2.0_openjdk8-alpine3.7:1.0
    working_dir: /app
    volumes:
      - ./app/src:/app/src
      - ./app/project:/app/project
      - ./app/build.sbt:/app/build.sbt
      - /tmp/receipts-target:/app/target
      - ./app/Dockerfile:/app/Dockerfile
      - $HOME/.ivy2:/root/.ivy2
      - $HOME/.sbt:/root/.sbt
    command: bash -c "sbt assembly && cp Dockerfile /app/target && cp /app/target/scala-2.12/receipts-rest-service-assembly-1.0.jar /app/target/receipts.jar"

  test:
    image: leonti/sbt_1.2.0_openjdk8-alpine3.7:1.0
    working_dir: /app
    volumes:
      - ./app/src:/app/src
      - ./app/project:/app/project
      - ./app/build.sbt:/app/build.sbt
      - /tmp/receipts-target-tests:/app/target
      - $HOME/.ivy2:/root/.ivy2
      - $HOME/.sbt:/root/.sbt
    command: sbt test

  integration-tests:
    image: leonti/sbt_1.2.0_openjdk8-alpine3.7:1.0
    environment:
      - APP_HOST_PORT=http://app:9000
      - WAIT_EXPRESSION=[ $$(curl --write-out %{http_code} --silent --output /dev/null "$$APP_HOST_PORT/config") = 200 ]
      - WAIT_SLEEP=2
      - WAIT_LOOPS=60
    depends_on:
      - app
    working_dir: /app
    volumes:
      - ./app/src:/app/src
      - ./app/project:/app/project
      - ./app/build.sbt:/app/build.sbt
      - /tmp/receipts-target-tests:/app/target
      - $HOME/.ivy2:/root/.ivy2
      - $HOME/.sbt:/root/.sbt
    command: bash -c "rm -rf /app/target/* && sbt clean && sbt it:test"
